### ISSUE TITLE
Support searching for multiple items

### ISSUE THREAD

**Issue by mikeerickson** [flesch/npms-cli#2]
```
$ npms search npms-cli cli-table cli-table2 truncate ...
```

Ala the way we can install multiple items using `npm install`

**Comment by mikeerickson** [comment]
In reviewing the api, it seems it (currently) only supports one term, thus you would have to make separate requests for each term and then bundle them all together in your result.

I have also asked to have the api enhanced to support multiple terms (and other items) so you would only be doing it as a patch.  Seems the best course of action would be to wait for api to add it.

Related post on api list

https://github.com/npms-io/npms-api/issues/29

**Comment by flesch** [comment]
It looks like the API does support multiple terms, at least from what I can tell.

<https://npms.io/search?term=react+redux+boilerplate> gives a different set of results than <https://npms.io/search?term=react+redux>, which is different than <https://npms.io/search?term=react>.

However, `npms search react redux boilerplate` returns siltently. `npms search react+redux+boilerplate` appears to work like it should though, so serializing that `argv._` array should fix it.
