### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by mikeerickson** [flesch/npms-cli#3]
There are currently no tests on this project (not a big deal at all).   Would you mind if I added some and issued a PR?

I am doing the #30daysOfTesting challenge so I figured this was a good place to get started for said challenge (I do testing on all my projects but looking to test outside my box)

- Mike

**Comment by flesch** [comment]
Absolutely — that would be amazing! What are you thinking of using (just curious, I don't have any preference, which can probably tell from the total lack of tests in the repo :stuck_out_tongue_winking_eye:)?

**Comment by mikeerickson** [comment]
I am thinking going with the standard tooling (mocha) but may also use Ava.

**Comment by mikeerickson** [comment]
@flesch Well, based on the conversation on the main repo, guess I don't need to worry about writing tests either.  Time to move onto other projects, no sense in duplicating work.  Looks like @dcrockwell has it all planned out (or at least what is conditions are) https://github.com/npms-io/npms-cli/issues/1

**Comment by mikeerickson** [comment]
So, do you have any take on the above mentioned comments?

**Comment by flesch** [comment]
I'm going to close this - I asked if I could publish one more release (to fix #5), but won't worry about adding tests.

**Comment by mikeerickson** [comment]
Figured as much :)
