### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by mikeerickson** [flesch/npms-cli#5]
Hey bud

went to use npms-cli this morning and seems to have stopped working.  Did they break something on the API to case it to break?

I had just referred to a colleague and it I got egg on face :-)

**Comment by mikeerickson** [comment]
Looks like the JSON result is now wrapped in a "module" object.  I have tweaked source locally to make it work.  Guessing this project will eventually die when they get their own CLI done.

I will use this one in the meantime, until official release.

**Comment by flesch** [comment]
Yeah, not sure if I should push fixes until they release something, continue with a "fork", or just let it go.

**Comment by mikeerickson** [comment]
What did you decide. I can continue with my local tweaks, but would be nice to at least have something working in the meantime.

**Comment by flesch** [comment]
I think I'll push one last thing. I'd like to have it at least working before something official is released. If you want to create a PR for what you've changed I could probably get it out this weekend.

**Comment by mikeerickson** [comment]
I will send a PR w/ my fixes later today (Saturday). It js 1:30am and I need some sleep. Should you add it before I PR, let me know 😜

**Comment by mikeerickson** [comment]
@flesch All done, fixed in the following PR https://github.com/flesch/npms-cli/pull/6 and closed.  Happy publishing 👍  💯
